apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dso-demo
  name: dso-demo
  namespace: dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dso-demo
  type: LoadBalancer
status:
  loadBalancer: {}
